using System.Text;
using Calculate;//don't know why this is neccessary since calculate is included in the csproj, May have to do with certain autogenerated parts of the .sln not being created 
                //due to me using vscode instead of visual studio

namespace CalculateTests;

public class ProgramTests
{
    //Write a test that sets these properties at construction time and then invokes the properties and verifies the expected behavior occurs
    //the properties can no longer be changed at construction time due to Program being a static class
    [Fact]
    public void WriteLine_Set_Behavior()
    {
        StringBuilder outStream = new();
        Program.WriteLine = text => outStream.Append(text); 

        Program.WriteLine("test");
        Assert.Equal("test", outStream.ToString());
    }

    [Fact]
    public void ReadLine_Set_Behavior()
    {
        Program.ReadLine = () => "test"; 
        Assert.Equal("test", Program.ReadLine());
    }
}